#!/bin/bash
MYSQL_CLEANUP_CMD="mysql --host=$MYSQL_DEST_HOST "

if [ ! -z "$MYSQL_DEST_PORT" ];
then
    MYSQL_CLEANUP_CMD="$MYSQL_CLEANUP_CMD --port=$MYSQL_DEST_PORT ";
fi

MYSQL_CLEANUP_CMD="$MYSQL_CLEANUP_CMD --user=$MYSQL_DEST_USER ";

if [ ! -z "$MYSQL_DEST_PASSWORD" ];
then
    MYSQL_CLEANUP_CMD="$MYSQL_CLEANUP_CMD --password=$MYSQL_DEST_PASSWORD";
fi

MYSQL_CLEANUP_CMD="$MYSQL_CLEANUP_CMD --execute='DROP DATABASE IF EXISTS $MYSQL_DEST_DB; CREATE DATABASE $MYSQL_DEST_DB';";
eval $MYSQL_CLEANUP_CMD
